Src/Facebook.Presentation.Web/ViewModels/User/UserProfileViewModel.cs
using System;
using System.Dynamic;
using System.IO;
using System.Web;
using Facebook.Business.Domain;
using Facebook.Business.Domain.Images;
using Facebook.Infrastructure.Contracts;

namespace Facebook.Presentation.Web.ViewModels.User
{
    public class UserProfileViewModel
    {
        #region Image


        public HttpPostedFileBase Image { get; set; }


        #endregion


        #region Personal Information



        public virtual bool? InterestedInMen { get; set; }


        public virtual bool? InterestedInWomen { get; set; }


        public virtual bool? LookingForFriendship { get; set; }


        public virtual bool? LookingForRelationship { get; set; }


        public virtual DateTime? BirthDay { get; set; }


        public virtual string HomeTown { get; set; }


        public virtual string AboutMe { get; set; }


        #endregion


        #region Contact Information




        public virtual string EMail { get; set; }


        public virtual bool? EMailOnlyForFriends { get; set; }


        public virtual int? MobileNumber { get; set; }


        public virtual bool? MobileNumberOnlyForFriends { get; set; }


        public string AddressInfo { get; set; }


        public virtual string City { get; set; }


        public virtual string State { get; set; }


        public virtual string Country { get; set; }


        public virtual bool? AddressOnlyForFriends { get; set; }


        #endregion


        public void Update(Business.Domain.Users.User user)
        {
            ContractUtil.NotNull(user);

            if(Image != null)
            {
                var format = Path.GetExtension(Image.FileName);
                var data = new byte[Image.InputStream.Length];
                Image.InputStream.Read(data, 0, data.Length);

                var img = new Image(data, format, "");
                user.SetPhoto(img);
            }

            if (State != user.Profile.ContactInformation.Address.State)
                user.Profile.ContactInformation.Address.State = State;

            if (AboutMe != user.Profile.PersonalInformation.AboutMe)
                user.Profile.PersonalInformation.AboutMe = AboutMe;

            if (City != user.Profile.ContactInformation.Address.City)
                user.Profile.ContactInformation.Address.City = City;

            if (BirthDay != user.Profile.PersonalInformation.BirthDay)
                user.Profile.PersonalInformation.BirthDay = BirthDay;

            if (HomeTown != user.Profile.PersonalInformation.HomeTown)
                user.Profile.PersonalInformation.HomeTown = HomeTown;

            if (EMail != user.Profile.ContactInformation.EMail)
                user.Profile.ContactInformation.EMail = EMail;

            if (EMailOnlyForFriends != user.Profile.ContactInformation.EMailOnlyForFriends)
                user.Profile.ContactInformation.EMailOnlyForFriends = EMailOnlyForFriends;

            if (Country != user.Profile.ContactInformation.Address.Country)
                user.Profile.ContactInformation.Address.Country = Country;

            if (AddressInfo != user.Profile.ContactInformation.Address.AddressInfo)
                user.Profile.ContactInformation.Address.AddressInfo = AddressInfo;

            if (AddressOnlyForFriends != user.Profile.ContactInformation.AddressOnlyForFriends)
                user.Profile.ContactInformation.AddressOnlyForFriends = AddressOnlyForFriends;

            if (InterestedInMen != user.Profile.PersonalInformation.InterestedInMen)
                user.Profile.PersonalInformation.InterestedInMen = InterestedInMen;

            if (InterestedInWomen != user.Profile.PersonalInformation.InterestedInWomen)
                user.Profile.PersonalInformation.InterestedInWomen = InterestedInWomen;

            if (LookingForFriendship != user.Profile.PersonalInformation.LookingForFriendship)
                user.Profile.PersonalInformation.LookingForFriendship = LookingForFriendship;

            if (LookingForRelationship != user.Profile.PersonalInformation.LookingForRelationship)
                user.Profile.PersonalInformation.LookingForRelationship = LookingForRelationship;

            if (MobileNumber != user.Profile.ContactInformation.MobileNumber)
                user.Profile.ContactInformation.MobileNumber = MobileNumber;

            if (MobileNumberOnlyForFriends != user.Profile.ContactInformation.MobileNumberOnlyForFriends)
                user.Profile.ContactInformation.MobileNumberOnlyForFriends = MobileNumberOnlyForFriends;
        }
    }
}

Src/Facebook.Presentation.Web/ViewModels/User/UserViewModel.cs
using System.Web.Mvc;
using Facebook.Business.Domain;

namespace Facebook.Presentation.Web.ViewModels.User
{
    public class UserViewModel
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string FacebookId { get; set; }

        
        public string Name { get; set; }

        [HiddenInput(DisplayValue = false)]
        public FriendshipStatus FriendshipStatus { get; set; }


        public ImageViewModel Photo { get; set; }
    }
}

Src/Facebook.Presentation.Web/Controllers/ImagesController.cs
using System.IO;
using System.Web;
using System.Web.Mvc;
using Facebook.Business.Domain.Images;
using Facebook.Data;

namespace Facebook.Presentation.Web.Controllers
{
    public class ImagesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ImagesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        public ActionResult GetImageFromId(int id)
        {
            var images = _unitOfWork.Images;
            var img = images.FindById(id);
            return new FileContentResult(img.Data, string.Format("image/{0}", img.Format));
        }

        //public FileContentResult GetImage(Image img)
        //{
        //    return new FileContentResult(img.Data, string.Format("image/{0}", img.Format));
        //}

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, string description)
        {
            var format = Path.GetExtension(file.FileName);
            var data = new byte[file.InputStream.Length];
            file.InputStream.Read(data, 0, data.Length);

            _unitOfWork.Images.Add(new Image(data, format, description));

            return null;
        }
    }
}

Src/Facebook.Presentation.Web/Controllers/PostsController.cs
using System.Web.Mvc;
using Facebook.Business.Domain;
using Facebook.Business.Domain.Facade;
using Facebook.Business.Domain.Facade.Posts;
using Facebook.Business.Domain.Posts;
using Facebook.Data;
using Facebook.Presentation.Web.Filters;
using Facebook.Presentation.Web.Security;
using Facebook.Presentation.Web.Utils;
using Facebook.Presentation.Web.ViewModels;
using Facebook.Presentation.Web.ViewModels.Posts;

namespace Facebook.Presentation.Web.Controllers
{
    public class PostsController : Controller
    {
        private readonly IUserProvider _userProvider;
        private readonly IPostsManagementService _postsManagementService;

        public PostsController(IPostsManagementService postsManagementService, IUserProvider userProvider)
        {
            _postsManagementService = postsManagementService;
            _userProvider = userProvider;
        }


        [MultipleResponseFormats]
        [AutoMap(typeof(object), typeof(PostCollectionViewModel))]
        public ActionResult Index(int page, int count)
        {
            var user = _userProvider.GetCurrentUser(_postsManagementService.UnitOfWork, HttpContext);
            var posts = _postsManagementService.GetPosts(user, page, count);

// ReSharper disable Mvc.InvalidModelType
// Reason a mapping will be permormed
            return PartialView(new { Posts = posts, OwnerId = user.Id, Page = page, Count = count });
// ReSharper restore Mvc.InvalidModelType
        }

        //[MultipleResponseFormats]
        [AutoMap(typeof(object), typeof(PostCollectionViewModel))]       
        public ActionResult GetPosts(int userId, int page, int count)
        {
            var user = _postsManagementService.UnitOfWork.Users.FindById(userId);
            var posts = _postsManagementService.GetOwnerPosts(user, page, count);

// ReSharper disable Mvc.InvalidModelType
            return PartialView("Index", new { Posts = posts, OwnerId = user.Id, Page = page, Count = count });
// ReSharper restore Mvc.InvalidModelType
        }

        [AutoMap(typeof(Post), typeof(PostViewModel))]
        public ActionResult Create(PostCreationViewModel creation)
        {
            // TODO: remove this fake data ...
            //string text = "Fake post text, Remember remove when ajax works !";

            var owner = _postsManagementService.UnitOfWork.Users.FindById(creation.OwnerId);
            var post = new Post(_userProvider.GetCurrentUser(_postsManagementService.UnitOfWork, HttpContext), 
                                owner,
                                DependencyResolver.Current.GetService<IDateTimeService>().Now(), 
                                creation.Text);

            _postsManagementService.UnitOfWork.Posts.Add(post);
            _postsManagementService.UnitOfWork.Commit();

         
// ReSharper disable Mvc.InvalidModelType
            return PartialView("_PostPartial", post);
// ReSharper restore Mvc.InvalidModelType
        }

        [AutoMap(typeof(Comment), typeof(CommentViewModel))]
        public ActionResult Comment(int ownerId, string text)
        {
            var user = _userProvider.GetCurrentUser(_postsManagementService.UnitOfWork, HttpContext);
            var comment = new Comment(user, text, DependencyResolver.Current.GetService<IDateTimeService>().Now());

            var post = _postsManagementService.UnitOfWork.Posts.FindById(ownerId);
            post.AddComment(comment);

            _postsManagementService.UnitOfWork.Commit();

// ReSharper disable Mvc.InvalidModelType
            return PartialView("_CommentPartial", comment);
// ReSharper restore Mvc.InvalidModelType
        }
    }
}

Src/Facebook.Presentation.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Facebook.Business.Domain;
using Facebook.Business.Domain.Facade.Friendship;
using Facebook.Business.Domain.Users;
using Facebook.Data;
using Facebook.Presentation.Web.Filters;
using Facebook.Presentation.Web.Security;
using Facebook.Presentation.Web.Utils;
using Facebook.Presentation.Web.ViewModels.User;

namespace Facebook.Presentation.Web.Controllers
{
    //[Authorize]
    public class UserController : Controller
    {
        private readonly IUserProvider _userProvider;
        private readonly IFriendshipManagementService _friendshipManagementService;

        public UserController(IUserProvider userProvider, 
                              IFriendshipManagementService friendshipManagementService)
        {
            _userProvider = userProvider;
            _friendshipManagementService = friendshipManagementService;
        }

        [HttpGet]
        [AutoMap(typeof(User), typeof(UserViewModel))]
        public ActionResult Home()
        {
            var user = _userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext);

// ReSharper disable Mvc.InvalidModelType
// Reasons: later mapping is performed ...
            return View(user);
// ReSharper restore Mvc.InvalidModelType
        }

        [AutoMap(typeof(object), typeof(UserViewModel))]
        public ActionResult Index(string keyword, int page = 1, int count = 10)
        {
            var user = _friendshipManagementService.UnitOfWork.Users.FindByKeyword(keyword);

            if (Equals(user, null))
                throw new InvalidOperationException(string.Format("No user exists with the current keyword: {0}", keyword));

            var status = _friendshipManagementService.GetFriendshipStatus(_userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext), user);
// ReSharper disable Mvc.InvalidModelType
            return View(new { User = user, FriendshipStatus = status });
// ReSharper restore Mvc.InvalidModelType
        }

        [HttpGet]
        [AutoMap(typeof(User), typeof(UserProfileViewModel))]
        public new ActionResult Profile()
        {
            var user = _userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext);

// ReSharper disable Mvc.InvalidModelType
// Reasons: later mapping is performed ...
            return View(user);
// ReSharper restore Mvc.InvalidModelType
        }

        [HttpPost]
        public new ActionResult Profile(UserProfileViewModel profile)
        {
            if (!ModelState.IsValid)
                return View(profile);

            var user = _userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext);
            profile.Update(user);
            _friendshipManagementService.UnitOfWork.Commit();
   
            return RedirectToAction("Home");
        }

        [AutoMap(typeof(IList<dynamic>), typeof(IList<UserViewModel>))]
        public ActionResult FindFriends(int page = 1, int count = 10)
        {
            var user = _userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext);
            var items = _friendshipManagementService.GetResquestsTo(user)
                                                    .Concat( _friendshipManagementService.GetPossiblesFriends(user))
                                                    .Paginate(page, count)
                                                    .Select(other => new  { User = other, FriendshipStatus = _friendshipManagementService.GetFriendshipStatus(user, other) })
                                                    .ToList();
          
// ReSharper disable Mvc.InvalidModelType
            return PartialView(items);
// ReSharper restore Mvc.InvalidModelType
        }
        
        public ActionResult AddFriend(int userId)
        {
            var other = _friendshipManagementService.UnitOfWork.Users.FindById(userId);
            _friendshipManagementService.SendRequest(_userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext), other);

            return null;
        }

        public ActionResult AcceptFriend(int userId)
        {
            var other = _friendshipManagementService.UnitOfWork.Users.FindById(userId);
            _friendshipManagementService.AcceptRequest(other, _userProvider.GetCurrentUser(_friendshipManagementService.UnitOfWork, HttpContext));

            return null;
        }
    }
}

Src/Facebook.Presentation.Web/Views/User/FindFriends.cshtml
@using Facebook.Business.Domain
@using Facebook.Presentation.Web.Utils
@model IList<Facebook.Presentation.Web.ViewModels.User.UserViewModel>




@foreach (var user in Model)
{
    <div>

        <div class="float-left">
            @Html.UserName(user)
        </div>

        @{
            var formId = "add-friend-form" + user.Id;
            var loadingId = "loading" + user.Id;
            var processingId = "processing" + user.Id;
            var action = user.FriendshipStatus == FriendshipStatus.NoRelation ? "AddFriend" : "AcceptFriend";
            var value = user.FriendshipStatus == FriendshipStatus.NoRelation ? "Add Friend" : "Accept Friend";
        }
        @using (Ajax.BeginForm(action,
                               "User",
                               new { userId = user.Id },
                               new AjaxOptions
                                   {
                                      UpdateTargetId = formId,
                                      InsertionMode = InsertionMode.Replace,
                                      LoadingElementId = processingId,
                                   },
                              new { id = formId, @class = "add-friend-form" }))
        {
            <input type="submit" value="@value" />
            <img src="~/Images/GsNJNwuI-UM.gif" style="display: none" id="@processingId"/>
        }

    </div>
    
    <div class="cleaner"></div>
}


Src/Facebook.Presentation.Web/Views/User/Home.cshtml
@using Facebook.Presentation.Web.Utils
@model Facebook.Presentation.Web.ViewModels.User.UserViewModel

@{
    var ajaxOpt = new AjaxOptions
                      {
                          UpdateTargetId = "container",
                          InsertionMode = InsertionMode.Replace,
                      };
}

<section id="container" class="content-wrapper">
    
    @{ Html.RenderAction("Index", "Posts", new { page = 1, count = 10 }); }

</section>


@section sidebar
{
    <section class="sidebar">
        <ol class="menu">
            
             <li class="menu-item">
                @Ajax.ActionLink("Posts", "Index", "Posts", new { page = 1, count = 10 }, ajaxOpt, new { @class = "menu-item-link" })
            </li>
            <li class="menu-item">
                @Ajax.ActionLink("Messages", "Index", "Messages", new { page = 1, count = 10 }, ajaxOpt, new { @class = "menu-item-link" })
            </li>
            <li class="menu-item">
                @Ajax.ActionLink("Notifications", "Index", "Notifications", new { page = 1, count = 10 }, ajaxOpt, new { @class = "menu-item-link" })
            </li>
            <li class="menu-item">
                @Ajax.ActionLink("Find Friends", "FindFriends", "User", new { page = 1, count = 10 }, ajaxOpt, new { @class = "menu-item-link" })
            </li>
             @*<li class="menu-item">
                @Html.ActionLink("Messages", "Index", "Messages", new  {Page = 1, Count = 10}, new {@class = "menu-item-link"})
            </li>
            <li class="menu-item">
                @Html.ActionLink("Notifications", "Index", "Notifications", new { page = 1, count = 10 }, new { @class = "menu-item-link" })
            </li>
            <li class="menu-item">
                @Html.ActionLink("Find Friends", "GetPossiblesFriends", "User", new { page = 1, count = 10 }, new { @class = "menu-item-link" })
            </li>*@
        </ol>
    </section>
}

@section featured
{
    <section class="featured">
        <img src="@Url.Action("GetImageFromId", "Images", new { id = Model.Photo.ImgId })" alt="@Model.Photo.Description"/>    
        <h3>@Html.UserName(Model)</h3>
        <div class="cleaner"></div>
    </section>
}




Src/Facebook.Presentation.Web/Views/User/Index.cshtml
@using Facebook.Business.Domain
@using Facebook.Presentation.Web.Utils
@using Facebook.Presentation.Web.ViewModels
@model Facebook.Presentation.Web.ViewModels.User.UserViewModel


<section id="container" class="content-wrapper">

    @{ Html.RenderAction("GetPosts", "Posts", new { userId = Model.Id, page = 1, count = 10 }); }

</section>




@section featured
{
    <section class="featured">
        <img src="@Url.Action("GetImageFromId", "Images", new { id = Model.Photo.ImgId })" alt="@Model.Photo.Description" class="float-left" width="100" height="100"/>
        <h3>@Html.UserName(Model)</h3>

        @if (Model.FriendshipStatus == FriendshipStatus.NoRelation)
        {
            var formId = "add-friend-form" + Model.Id;
            var processingId = "processing" + Model.Id;

            using (Ajax.BeginForm("AddFriend",
                                  "User",
                                  new { userId = Model.Id },
                                  new AjaxOptions
                                  {
                                      UpdateTargetId = formId,
                                      InsertionMode = InsertionMode.Replace,
                                      LoadingElementId = processingId,
                                  },
                              new { id = formId, @class = "add-friend-form" }))
            {
                <input type="submit" value="Add Friend" />
                <img src="~/Images/GsNJNwuI-UM.gif" style="display: none" id="@processingId"/>
            }
        }
        <div class="cleaner"></div>
    </section>
}

Src/Facebook.Presentation.Web/Views/User/Profile.cshtml
@model Facebook.Presentation.Web.ViewModels.User.UserProfileViewModel

@using (Html.BeginForm("Profile", "User", FormMethod.Post, new { @class = "profile-edit-form", enctype = "multipart/form-data" }))
{
    <div class="personal-info-edit">
        @Html.LabelFor(model => model.AboutMe)
        @Html.EditorFor(model => model.AboutMe)
        <br/>

        @Html.LabelFor(model => model.BirthDay)
        @Html.EditorFor(model => model.BirthDay)
        <br/>

        @Html.LabelFor(model => model.HomeTown)
        @Html.EditorFor(model => model.HomeTown)
        <br/>

        @Html.LabelFor(model => model.LookingForFriendship)
        @Html.EditorFor(model => model.LookingForFriendship)
        <br/>

        @Html.LabelFor(model => model.LookingForRelationship)
        @Html.EditorFor(model => model.LookingForRelationship)
        <br/>

        @Html.LabelFor(model => model.InterestedInMen)
        @Html.EditorFor(model => model.InterestedInMen)
        <br/>

        @Html.LabelFor(model => model.InterestedInWomen)
        @Html.EditorFor(model => model.InterestedInWomen)
    </div>
    
    <div class="contact-info-edit">
        @Html.LabelFor(model => model.EMail)
        @Html.EditorFor(model => model.EMail)
        @Html.LabelFor(model => model.EMailOnlyForFriends)
        @Html.EditorFor(model => model.EMailOnlyForFriends)
        <br/>
        
        @Html.LabelFor(model => model.MobileNumber)
        @Html.EditorFor(model => model.MobileNumber)
        @Html.LabelFor(model => model.MobileNumberOnlyForFriends)
        @Html.EditorFor(model => model.MobileNumberOnlyForFriends)
        <br/>
        
        <div class="address-info-edit">
            @Html.LabelFor(model => model.Country)
            @Html.EditorFor(model => model.Country)
        </div>
    </div>
    
    <input type="file" name="Image" class="file-input"/>
    
    <input type="submit" value="OK"/>
}